all: arith1 arith2

arith1: arith1.c
	gcc -g -Wall -Wextra -o arith1 arith1.c

arith2: arith2.c
	gcc -g -Wall -Wextra -o arith2 arith2.c

q4: q4.c
	gcc -g -Wall -Wextra -o q4 q4.c

clean:
	rm arith1 arith2
